version: "3.9"
services:
  mongo:
    container_name: mongo5
    image: mongo:5.0.5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: twd-api
    build: .
    image: twd-api
    restart: always
    volumes:
      - ./:/usr/src/twd-api/
    ports:
      - "3000:3000"
